project_name: terraform-controller
builds:
  - id: mybuild
    main: ./cmd/controller/main.go
    goos:
      - linux
      - darwin
      
    goarch:
      - amd64
      - arm64
    flags:
      - -v
    ldflags:
      - -s -w
archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
      - config.yaml
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

