apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-manager
rules:
- apiGroups: ["alustan.io"]
  resources: ["terraforms"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]



