apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: terraforms.alustan.io  
spec:
  group: alustan.io
  names:
    plural: terraforms
    singular: terraform
    kind: Terraform
    shortNames:
      - tf
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                variables:
                  type: object
                backend:
                  type: object
                  properties:
                    provider:
                      type: string
                  additionalProperties: true
                scripts:
                  type: object
                  properties:
                    apply:
                      type: object
                      properties:
                        inline:
                          type: string
                        configMapRef:
                          type: object
                          properties:
                            name:
                              type: string
                            key:
                              type: string
                    destroy:
                      type: object
                      properties:
                        inline:
                          type: string
                        configMapRef:
                          type: object
                          properties:
                            name:
                              type: string
                            key:
                              type: string
                gitRepo:
                  type: object
                  properties:
                    url:
                      type: string
                    branch:
                      type: string
                    sshKeySecret:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                containerRegistry:
                  type: object
                  properties:
                    imageName:
                      type: string
                    secretRef:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
            status:
              type: object
              properties:
                state:
                  type: string
                message:
                  type: string
      subresources:
        status: {}
