# kubectl create configmap terraform-scripts --from-file=apply-script=apply_script.sh --from-file=destroy-script=destroy_script.sh
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: terraform-scripts
# data:
#   apply-script.sh: |
#     #!/bin/bash
#     echo "This is the apply script"
#   destroy-script.sh: |
#     #!/bin/bash
#     echo "This is the destroy script"


# kubectl create secret docker-registry my-registry-secret \
#   --docker-server=https://index.docker.io/v1/ \
#   --docker-username=<USERNAME> \
#   --docker-password=<PASSWORD> \
#   --docker-email=<EMAIL>


apiVersion: alustan.io/v1alpha1
kind: Terraform
metadata:
  name: example-terraformconfig
  namespace: default
spec:
  variables:
    var1: value1
    var2: value2
  backend:
    provider: aws
    s3: s3-store
    dynamoDB: db-table
    region: us-east-1
  scripts:
    apply: 
     inline: |
       terraform apply -auto-approve
    destroy: 
     inline: |
        terraform destroy -auto-approve
  gitRepo:
    url: git@github.com:example/terraform-repo
    branch: main
    sshKeySecret:
      name: my-ssh-secret
      key: ssh-privatekey
  containerRegistry:
    imageName: docker.io/alustan/terrform (image name to be built and push by the controller)
    secretRef:
      name: my-dockerhub-secret
      key: dockerhub-cred
