apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.persistentVolumeClaim.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.volumes.storageClassName }}
