---
name: Release helm chart
on:
  push:
    tags:
      - 'v*.*.*'  # Trigger the workflow on version tags
jobs:
  release-helm:
    name: Release helm chart
    permissions:
      contents: write
    env:
      HELM_EXPERIMENTAL_OCI: 1
    runs-on: ubuntu-22.04
 
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: install helm
        uses: Azure/setup-helm@v4
        with:
          version: 3.8.0

      - name: login to ghcr.io using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/alustan/terraform-controller-helm --username ${{ github.repository_owner }} --password-stdin
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: save helm chart to local registry
        run: |
          helm package ${{ github.workspace }}/helm/terraform-controller-helm/

      - name: publish chart to Docker Hub
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          helm push terraform-controller-helm-${VERSION}.tgz oci://registry-1.docker.io/alustan
